{% set name = "inline-snapshot" %}
{% set version = "0.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/inline_snapshot-{{ version }}.tar.gz
  sha256: de85c5dfd31426c51b2820a3acb4569153fb62414a6a9833378b79859b869763

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - asttokens >=2.0.5
    - black >=23.3.0
    - click >=8.1.4
    - executing >=2.0.0
    - rich >=13.7.1
    - toml >=0.10.2
    - types-toml >=0.10.8.7
    - typing-extensions

test:
  imports:
    - inline_snapshot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/15r10nk/inline-snapshots
  summary: golden master/snapshot/approval testing library which puts the values right into your source code
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wolfv
