schema_version: 1

context:
  name: inline-snapshot
  version: 0.13.4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/inline_snapshot-${{ version }}.tar.gz
  sha256: 4225b73b6f8807d780424aee63e39a3bfa7688851d9cd90579d4b164b2d2c870

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - asttokens >=2.0.5
    - black >=23.3.0
    - click >=8.1.4
    - executing >=2.0.0
    - rich >=13.7.1
    - toml >=0.10.2
    - types-toml >=0.10.8.7
    - typing-extensions

tests:
  - python:
      imports:
        - inline_snapshot
      pip_check: true

about:
  summary: golden master/snapshot/approval testing library which puts the values right into your source code
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/15r10nk/inline-snapshots

extra:
  recipe-maintainers:
    - moritzwilksch
    - wolfv
