schema_version: 1

context:
  name: inline-snapshot
  version: "0.23.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/inline_snapshot-${{ version }}.tar.gz
  sha256: 872d027b1eae4e3e3b4028e0d46128bafbf62889a2424a2667dbe4b69cb1ffdf

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - asttokens >=2.0.5
    - executing >=2.2.0
    - rich >=13.7.1
    - tomli >=2.0.0
    - pytest >=8.3.4

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - inline_snapshot
      pip_check: true

about:
  summary: golden master/snapshot/approval testing library which puts the values right into your source code
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/15r10nk/inline-snapshots

extra:
  recipe-maintainers:
    - moritzwilksch
    - wolfv
